// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from "./client";
import type {
  GetBallotData,
  GetBallotResponses,
  GetBallotErrors,
  CreateElectionData,
  CreateElectionResponses,
  CreateElectionErrors,
  SetElectionMembersData,
  SetElectionMembersResponses,
  SetElectionMembersErrors,
  DeleteNominationData,
  DeleteNominationResponses,
  DeleteNominationErrors,
  GetNominationData,
  GetNominationResponses,
  GetNominationErrors,
  SubmitNominationData,
  SubmitNominationResponses,
  SubmitNominationErrors,
  GetPublicNominationData,
  GetPublicNominationResponses,
  GetPublicNominationErrors,
  GenerateOtpData,
  GenerateOtpResponses,
  GenerateOtpErrors,
  SubmitOtpData,
  SubmitOtpResponses,
  SubmitOtpErrors,
  GetElectionStateData,
  GetElectionStateResponses,
  GetElectionStateErrors,
  AdminTransitionElectionStateData,
  AdminTransitionElectionStateResponses,
  AdminTransitionElectionStateErrors,
  DeleteVoteData,
  DeleteVoteResponses,
  DeleteVoteErrors,
  GetVoteData,
  GetVoteResponses,
  GetVoteErrors,
  SubmitVoteData,
  SubmitVoteResponses,
  SubmitVoteErrors,
} from "./types.gen";
import {
  zGetBallotData,
  zCreateElectionData,
  zSetElectionMembersData,
  zDeleteNominationData,
  zGetNominationData,
  zSubmitNominationData,
  zGetPublicNominationData,
  zGenerateOtpData,
  zSubmitOtpData,
  zGetElectionStateData,
  zAdminTransitionElectionStateData,
  zDeleteVoteData,
  zGetVoteData,
  zSubmitVoteData,
} from "./zod.gen";
import { client } from "./client.gen";
import {
  getNominationResponseTransformer,
  getPublicNominationResponseTransformer,
  submitOtpResponseTransformer,
  getElectionStateResponseTransformer,
  getVoteResponseTransformer,
} from "./transformers.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get the current ballot
 */
export const getBallot = <ThrowOnError extends boolean = false>(
  options?: Options<GetBallotData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetBallotResponses, GetBallotErrors, ThrowOnError>({
    requestValidator: async (data) => {
      return await zGetBallotData.parseAsync(data);
    },
    security: [
      {
        in: "cookie",
        name: "SESSION",
        type: "apiKey",
      },
    ],
    url: "/api/v1/ballot",
    ...options,
  });
};

/**
 * Create an election
 */
export const createElection = <ThrowOnError extends boolean = false>(
  options: Options<CreateElectionData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateElectionResponses,
    CreateElectionErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zCreateElectionData.parseAsync(data);
    },
    security: [
      {
        in: "cookie",
        name: "SESSION",
        type: "apiKey",
      },
    ],
    url: "/api/v1/elections",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Set the member list for an election
 */
export const setElectionMembers = <ThrowOnError extends boolean = false>(
  options: Options<SetElectionMembersData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    SetElectionMembersResponses,
    SetElectionMembersErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zSetElectionMembersData.parseAsync(data);
    },
    security: [
      {
        in: "cookie",
        name: "SESSION",
        type: "apiKey",
      },
    ],
    url: "/api/v1/elections/{election_id}/members",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete self-nomination
 * Deletes an existing self-nomination for the current election. If an election is running, this route will always return as it succeeded even if a nomination did not exist.
 */
export const deleteNomination = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteNominationData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteNominationResponses,
    DeleteNominationErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zDeleteNominationData.parseAsync(data);
    },
    security: [
      {
        in: "cookie",
        name: "SESSION",
        type: "apiKey",
      },
    ],
    url: "/api/v1/nomination",
    ...options,
  });
};

/**
 * Get self-nomination
 * Retrieves an existing self-nomination (if any) for the current election.
 */
export const getNomination = <ThrowOnError extends boolean = false>(
  options?: Options<GetNominationData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetNominationResponses, GetNominationErrors, ThrowOnError>(
    {
      requestValidator: async (data) => {
        return await zGetNominationData.parseAsync(data);
      },
      responseTransformer: getNominationResponseTransformer,
      security: [
        {
          in: "cookie",
          name: "SESSION",
          type: "apiKey",
        },
      ],
      url: "/api/v1/nomination",
      ...options,
    },
  );
};

/**
 * Submit self-nomination
 * Creates a self-nomination for the current election, replacing an existing one.
 */
export const submitNomination = <ThrowOnError extends boolean = false>(
  options: Options<SubmitNominationData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    SubmitNominationResponses,
    SubmitNominationErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zSubmitNominationData.parseAsync(data);
    },
    security: [
      {
        in: "cookie",
        name: "SESSION",
        type: "apiKey",
      },
    ],
    url: "/api/v1/nomination",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get a public nomination by ID
 */
export const getPublicNomination = <ThrowOnError extends boolean = false>(
  options: Options<GetPublicNominationData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetPublicNominationResponses,
    GetPublicNominationErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zGetPublicNominationData.parseAsync(data);
    },
    responseTransformer: getPublicNominationResponseTransformer,
    security: [
      {
        in: "cookie",
        name: "SESSION",
        type: "apiKey",
      },
    ],
    url: "/api/v1/nomination/{nomination_id}",
    ...options,
  });
};

/**
 * Generate an OTP code
 */
export const generateOtp = <ThrowOnError extends boolean = false>(
  options: Options<GenerateOtpData, ThrowOnError>,
) => {
  return (options.client ?? client).post<GenerateOtpResponses, GenerateOtpErrors, ThrowOnError>({
    requestValidator: async (data) => {
      return await zGenerateOtpData.parseAsync(data);
    },
    url: "/api/v1/otp/generate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Submit an OTP to enter a session
 */
export const submitOtp = <ThrowOnError extends boolean = false>(
  options: Options<SubmitOtpData, ThrowOnError>,
) => {
  return (options.client ?? client).post<SubmitOtpResponses, SubmitOtpErrors, ThrowOnError>({
    requestValidator: async (data) => {
      return await zSubmitOtpData.parseAsync(data);
    },
    responseTransformer: submitOtpResponseTransformer,
    url: "/api/v1/otp/submit",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get the current election state
 */
export const getElectionState = <ThrowOnError extends boolean = false>(
  options?: Options<GetElectionStateData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetElectionStateResponses,
    GetElectionStateErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zGetElectionStateData.parseAsync(data);
    },
    responseTransformer: getElectionStateResponseTransformer,
    security: [
      {
        in: "cookie",
        name: "SESSION",
        type: "apiKey",
      },
    ],
    url: "/api/v1/state",
    ...options,
  });
};

/**
 * Transition the election state
 */
export const adminTransitionElectionState = <ThrowOnError extends boolean = false>(
  options: Options<AdminTransitionElectionStateData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    AdminTransitionElectionStateResponses,
    AdminTransitionElectionStateErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAdminTransitionElectionStateData.parseAsync(data);
    },
    security: [
      {
        in: "cookie",
        name: "SESSION",
        type: "apiKey",
      },
    ],
    url: "/api/v1/state",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete your current vote
 */
export const deleteVote = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteVoteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<DeleteVoteResponses, DeleteVoteErrors, ThrowOnError>({
    requestValidator: async (data) => {
      return await zDeleteVoteData.parseAsync(data);
    },
    security: [
      {
        in: "cookie",
        name: "SESSION",
        type: "apiKey",
      },
    ],
    url: "/api/v1/vote",
    ...options,
  });
};

/**
 * Get your current vote
 */
export const getVote = <ThrowOnError extends boolean = false>(
  options?: Options<GetVoteData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetVoteResponses, GetVoteErrors, ThrowOnError>({
    requestValidator: async (data) => {
      return await zGetVoteData.parseAsync(data);
    },
    responseTransformer: getVoteResponseTransformer,
    security: [
      {
        in: "cookie",
        name: "SESSION",
        type: "apiKey",
      },
    ],
    url: "/api/v1/vote",
    ...options,
  });
};

/**
 * Submit or update your current vote
 */
export const submitVote = <ThrowOnError extends boolean = false>(
  options: Options<SubmitVoteData, ThrowOnError>,
) => {
  return (options.client ?? client).put<SubmitVoteResponses, SubmitVoteErrors, ThrowOnError>({
    requestValidator: async (data) => {
      return await zSubmitVoteData.parseAsync(data);
    },
    security: [
      {
        in: "cookie",
        name: "SESSION",
        type: "apiKey",
      },
    ],
    url: "/api/v1/vote",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};
