// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetNominationResponse,
  GetPublicNominationResponse,
  SubmitOtpResponse,
  GetElectionStateResponse,
  GetVoteResponse,
  GetHealthResponse,
} from "./types.gen";

const nominationSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

export const getNominationResponseTransformer = async (
  data: any,
): Promise<GetNominationResponse> => {
  data = nominationSchemaResponseTransformer(data);
  return data;
};

const publicNominationSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

export const getPublicNominationResponseTransformer = async (
  data: any,
): Promise<GetPublicNominationResponse> => {
  data = publicNominationSchemaResponseTransformer(data);
  return data;
};

const submitOtpResponseBodySchemaResponseTransformer = (data: any) => {
  data.expiry = new Date(data.expiry);
  return data;
};

export const submitOtpResponseTransformer = async (data: any): Promise<SubmitOtpResponse> => {
  data = submitOtpResponseBodySchemaResponseTransformer(data);
  return data;
};

const getElectionStateResponseBodySchemaResponseTransformer = (data: any) => {
  if (data.state_created_at) {
    data.state_created_at = new Date(data.state_created_at);
  }
  return data;
};

export const getElectionStateResponseTransformer = async (
  data: any,
): Promise<GetElectionStateResponse> => {
  data = getElectionStateResponseBodySchemaResponseTransformer(data);
  return data;
};

const voteSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

export const getVoteResponseTransformer = async (data: any): Promise<GetVoteResponse> => {
  data = voteSchemaResponseTransformer(data);
  return data;
};

const healthOutputSchemaResponseTransformer = (data: any) => {
  data.checked = new Date(data.checked);
  return data;
};

export const getHealthResponseTransformer = async (data: any): Promise<GetHealthResponse> => {
  data = healthOutputSchemaResponseTransformer(data);
  return data;
};
