// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zCheckResult = z.object({
  error: z.unknown().optional(),
  status: z.string(),
  timestamp: z.string().datetime().optional(),
});

export const zCreateElectionInputBody = z.object({
  $schema: z.string().url().readonly().optional(),
  name: z.string(),
});

export const zCreateElectionResponseBody = z.object({
  $schema: z.string().url().readonly().optional(),
  election_id: z.string(),
});

export const zElectionMemberListSetInputBody = z.object({
  $schema: z.string().url().readonly().optional(),
  zids: z.union([z.array(z.string()), z.null()]),
});

export const zErrorDetail = z.object({
  location: z.string().optional(),
  message: z.string().optional(),
  value: z.unknown().optional(),
});

export const zErrorModel = z.object({
  $schema: z.string().url().readonly().optional(),
  detail: z.string().optional(),
  errors: z.union([z.array(zErrorDetail), z.null()]).optional(),
  instance: z.string().url().optional(),
  status: z.coerce.bigint().optional(),
  title: z.string().optional(),
  type: z.string().url().optional().default("about:blank"),
});

export const zGenerateOtpInputBody = z.object({
  $schema: z.string().url().readonly().optional(),
  zid: z.string().regex(/^z[0-9]{7}$/),
});

export const zGetElectionStateResponseBody = z.object({
  $schema: z.string().url().readonly().optional(),
  election_id: z.string().optional(),
  state: z.enum([
    "NO_ELECTION",
    "CLOSED",
    "NOMINATIONS_OPEN",
    "NOMINATIONS_CLOSED",
    "VOTING_OPEN",
    "VOTING_CLOSED",
    "RESULTS",
    "END",
  ]),
  state_created_at: z.string().datetime().optional(),
});

export const zHealthOutput = z.object({
  checked: z.string().datetime(),
  details: z.record(zCheckResult).optional(),
  health_status: z.enum(["up", "down", "unknown"]),
  info: z.record(z.unknown()).optional(),
});

export const zNomination = z.object({
  $schema: z.string().url().readonly().optional(),
  candidate_name: z.string(),
  candidate_statement: z.string(),
  candidate_zid: z.string(),
  contact_email: z.string(),
  created_at: z.string().datetime(),
  discord_username: z.string(),
  election_id: z.string(),
  executive_roles: z.union([
    z
      .array(
        z.enum([
          "president",
          "secretary",
          "treasurer",
          "arc_delegate",
          "edi_officer",
          "grievance_officer",
        ]),
      )
      .min(1)
      .max(6),
    z.null(),
  ]),
  nomination_id: z.string(),
  updated_at: z.string().datetime(),
  url: z.string().optional(),
});

export const zPublicNomination = z.object({
  $schema: z.string().url().readonly().optional(),
  candidate_name: z.string(),
  candidate_statement: z.string(),
  created_at: z.string().datetime(),
  discord_username: z.string(),
  election_id: z.string(),
  executive_roles: z.union([z.array(z.string()), z.null()]),
  nomination_id: z.string(),
  updated_at: z.string().datetime(),
  url: z.string().optional(),
});

export const zPublicBallot = z.object({
  $schema: z.string().url().readonly().optional(),
  candidates: z.record(z.union([z.array(zPublicNomination), z.null()])),
  election_id: z.string(),
  has_voted: z.boolean(),
});

export const zSubmitNomination = z.object({
  $schema: z.string().url().readonly().optional(),
  candidate_name: z.string().min(2).max(100),
  candidate_statement: z.string().min(50).max(2000),
  contact_email: z.string().email(),
  discord_username: z.string().min(2).max(32),
  executive_roles: z.union([
    z
      .array(
        z.enum([
          "president",
          "secretary",
          "treasurer",
          "arc_delegate",
          "edi_officer",
          "grievance_officer",
        ]),
      )
      .min(1)
      .max(6),
    z.null(),
  ]),
  url: z.string().url().optional(),
});

export const zSubmitNominationResponseBody = z.object({
  $schema: z.string().url().readonly().optional(),
  nomination_id: z.string(),
});

export const zSubmitOtpInputBody = z.object({
  $schema: z.string().url().readonly().optional(),
  otp: z.string().regex(/^[0-9]{6}$/),
  zid: z.string().regex(/^z[0-9]{7}$/),
});

export const zSubmitOtpResponseBody = z.object({
  $schema: z.string().url().readonly().optional(),
  expiry: z.string().datetime(),
  is_admin: z.boolean(),
  zid: z.string().regex(/^z[0-9]{7}$/),
});

export const zSubmitVoteBody = z.object({
  $schema: z.string().url().readonly().optional(),
  positions: z.record(z.string()),
});

export const zTransitionElectionStateBody = z.object({
  $schema: z.string().url().readonly().optional(),
  state: z.enum([
    "CLOSED",
    "NOMINATIONS_OPEN",
    "NOMINATIONS_CLOSED",
    "VOTING_OPEN",
    "VOTING_CLOSED",
    "RESULTS",
    "END",
  ]),
});

export const zVote = z.object({
  $schema: z.string().url().readonly().optional(),
  created_at: z.string().datetime(),
  positions: z.record(z.string()),
  updated_at: z.string().datetime(),
});

export const zCreateElectionInputBodyWritable = z.object({
  name: z.string(),
});

export const zCreateElectionResponseBodyWritable = z.object({
  election_id: z.string(),
});

export const zElectionMemberListSetInputBodyWritable = z.object({
  zids: z.union([z.array(z.string()), z.null()]),
});

export const zErrorModelWritable = z.object({
  detail: z.string().optional(),
  errors: z.union([z.array(zErrorDetail), z.null()]).optional(),
  instance: z.string().url().optional(),
  status: z.coerce.bigint().optional(),
  title: z.string().optional(),
  type: z.string().url().optional().default("about:blank"),
});

export const zGenerateOtpInputBodyWritable = z.object({
  zid: z.string().regex(/^z[0-9]{7}$/),
});

export const zGetElectionStateResponseBodyWritable = z.object({
  election_id: z.string().optional(),
  state: z.enum([
    "NO_ELECTION",
    "CLOSED",
    "NOMINATIONS_OPEN",
    "NOMINATIONS_CLOSED",
    "VOTING_OPEN",
    "VOTING_CLOSED",
    "RESULTS",
    "END",
  ]),
  state_created_at: z.string().datetime().optional(),
});

export const zNominationWritable = z.object({
  candidate_name: z.string(),
  candidate_statement: z.string(),
  candidate_zid: z.string(),
  contact_email: z.string(),
  created_at: z.string().datetime(),
  discord_username: z.string(),
  election_id: z.string(),
  executive_roles: z.union([
    z
      .array(
        z.enum([
          "president",
          "secretary",
          "treasurer",
          "arc_delegate",
          "edi_officer",
          "grievance_officer",
        ]),
      )
      .min(1)
      .max(6),
    z.null(),
  ]),
  nomination_id: z.string(),
  updated_at: z.string().datetime(),
  url: z.string().optional(),
});

export const zPublicNominationWritable = z.object({
  candidate_name: z.string(),
  candidate_statement: z.string(),
  created_at: z.string().datetime(),
  discord_username: z.string(),
  election_id: z.string(),
  executive_roles: z.union([z.array(z.string()), z.null()]),
  nomination_id: z.string(),
  updated_at: z.string().datetime(),
  url: z.string().optional(),
});

export const zPublicBallotWritable = z.object({
  candidates: z.record(z.union([z.array(zPublicNominationWritable), z.null()])),
  election_id: z.string(),
  has_voted: z.boolean(),
});

export const zSubmitNominationWritable = z.object({
  candidate_name: z.string().min(2).max(100),
  candidate_statement: z.string().min(50).max(2000),
  contact_email: z.string().email(),
  discord_username: z.string().min(2).max(32),
  executive_roles: z.union([
    z
      .array(
        z.enum([
          "president",
          "secretary",
          "treasurer",
          "arc_delegate",
          "edi_officer",
          "grievance_officer",
        ]),
      )
      .min(1)
      .max(6),
    z.null(),
  ]),
  url: z.string().url().optional(),
});

export const zSubmitNominationResponseBodyWritable = z.object({
  nomination_id: z.string(),
});

export const zSubmitOtpInputBodyWritable = z.object({
  otp: z.string().regex(/^[0-9]{6}$/),
  zid: z.string().regex(/^z[0-9]{7}$/),
});

export const zSubmitOtpResponseBodyWritable = z.object({
  expiry: z.string().datetime(),
  is_admin: z.boolean(),
  zid: z.string().regex(/^z[0-9]{7}$/),
});

export const zSubmitVoteBodyWritable = z.object({
  positions: z.record(z.string()),
});

export const zTransitionElectionStateBodyWritable = z.object({
  state: z.enum([
    "CLOSED",
    "NOMINATIONS_OPEN",
    "NOMINATIONS_CLOSED",
    "VOTING_OPEN",
    "VOTING_CLOSED",
    "RESULTS",
    "END",
  ]),
});

export const zVoteWritable = z.object({
  created_at: z.string().datetime(),
  positions: z.record(z.string()),
  updated_at: z.string().datetime(),
});

export const zGetBallotData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * OK
 */
export const zGetBallotResponse = zPublicBallot;

export const zCreateElectionData = z.object({
  body: zCreateElectionInputBodyWritable,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * OK
 */
export const zCreateElectionResponse = zCreateElectionResponseBody;

export const zSetElectionMembersData = z.object({
  body: zElectionMemberListSetInputBodyWritable,
  path: z.object({
    election_id: z.string(),
  }),
  query: z.never().optional(),
});

/**
 * No Content
 */
export const zSetElectionMembersResponse = z.void();

export const zDeleteNominationData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * No Content
 */
export const zDeleteNominationResponse = z.void();

export const zGetNominationData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * OK
 */
export const zGetNominationResponse = zNomination;

export const zSubmitNominationData = z.object({
  body: zSubmitNominationWritable,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * OK
 */
export const zSubmitNominationResponse = zSubmitNominationResponseBody;

export const zGetPublicNominationData = z.object({
  body: z.never().optional(),
  path: z.object({
    nomination_id: z.string(),
  }),
  query: z.never().optional(),
});

/**
 * OK
 */
export const zGetPublicNominationResponse = zPublicNomination;

export const zGenerateOtpData = z.object({
  body: zGenerateOtpInputBodyWritable,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * No Content
 */
export const zGenerateOtpResponse = z.void();

export const zSubmitOtpData = z.object({
  body: zSubmitOtpInputBodyWritable,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * OK
 */
export const zSubmitOtpResponse = zSubmitOtpResponseBody;

export const zGetElectionStateData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * OK
 */
export const zGetElectionStateResponse = zGetElectionStateResponseBody;

export const zAdminTransitionElectionStateData = z.object({
  body: zTransitionElectionStateBodyWritable,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * No Content
 */
export const zAdminTransitionElectionStateResponse = z.void();

export const zDeleteVoteData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * No Content
 */
export const zDeleteVoteResponse = z.void();

export const zGetVoteData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * OK
 */
export const zGetVoteResponse = zVote;

export const zSubmitVoteData = z.object({
  body: zSubmitVoteBodyWritable,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * No Content
 */
export const zSubmitVoteResponse = z.void();
