name: Prettier
on:
  workflow_call:
    inputs:
      subrepo:
        required: true
        type: string
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: prettier
        uses: EPMatt/reviewdog-action-prettier@93fb51ed5da157256e1d8c998fb249837304050c # v1.2.0
        with:
          fail_on_error: true
          filter_mode: nofilter
          level: warning
          reporter: github-check
          workdir: ${{ inputs.subrepo }}
